name: Publish package to GitHub Packages
on:
  push:
    branches: [ "test" ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - name: checking container 
        run: |
          echo I am in container..... 
          ls -a 
          echo checking java version .....
          java --version
          echo Is git installed.......?
          git --version
          echo Is build tools installed...?
          mvn --version   
#       - uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'adopt'
#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
          
          
          
          
